# Tensor  
ver 2.9.0 + cu128

モデルの入力と出力、そしてモデルのパラメータを示すためにテンソルを使用する。  
- GPUを利用できる
PyTorchのTensorはGPU上での高速計算が可能。  
- 自動微分  
AIの学習には「微分の計算（勾配計算）」が必要。  
PyTorchのTensorには、「自分に対してどのような計算が行われたか」を記憶する機能が備わっている。   
学習時に loss.backward() を使用すると、微分計算が可能。NumPyにはこの自動追跡機能がない。  


In [86]:
import torch
import numpy as np

## 初期化

- 直接データからテンソルを作成  
`torch.tensor`

In [87]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [88]:
print(type(data))
print(type(x_data))

<class 'list'>
<class 'torch.Tensor'>


In [89]:
print(data)
print(x_data)

[[1, 2], [3, 4]]
tensor([[1, 2],
        [3, 4]])


- NumPy配列から  
`torch.from_numpy`

In [90]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [91]:
type(np_array)

numpy.ndarray

In [92]:
np_array, x_np

(array([[1, 2],
        [3, 4]]),
 tensor([[1, 2],
         [3, 4]]))

- テンソルの変換  
`torch.ones_like`：要素を1に変換  
`torch.rand_like`：要素をランダムに変換

In [93]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor:\n {x_ones}")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} ")

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])
Random Tensor: 
 tensor([[0.0920, 0.5726],
        [0.6412, 0.8529]]) 


- shapeから変換  
`torch.rand`：ランダム  
`torch.ones`：1  
`torch.zeros`：0

In [94]:
shape = (2,3,) # 2行3列
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} ")
print(f"Ones Tensor: \n {ones_tensor} ")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9005, 0.0561, 0.5791],
        [0.7628, 0.0825, 0.5887]]) 
Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 属性

In [95]:
tensor = torch.rand(3,4)

In [96]:
tensor

tensor([[0.2418, 0.9413, 0.9458, 0.1546],
        [0.6489, 0.1944, 0.4306, 0.4555],
        [0.0841, 0.2483, 0.0735, 0.3932]])

In [97]:
tensor.shape

torch.Size([3, 4])

In [98]:
tensor.dtype

torch.float32

In [99]:
tensor.device

device(type='cpu')

In [100]:
tensor2 = torch.tensor(data)
print(data)
print(tensor2.dtype) # 中の数値の型に依存するんだね。

[[1, 2], [3, 4]]
torch.int64


In [101]:
data2 = [[1,2], [0.1, 1]]
tensor3 = torch.tensor(data2)
print(tensor3)
print(tensor3.dtype)  # へー

tensor([[1.0000, 2.0000],
        [0.1000, 1.0000]])
torch.float32


## 演算

演算が1200もあるらしい。演算方法？  
デフォルトでは、テンソルはCPU上で生成される。

In [102]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

In [103]:
tensor = torch.rand(4, 3)
tensor

tensor([[0.0315, 0.1096, 0.5357],
        [0.9299, 0.7199, 0.1575],
        [0.1956, 0.3469, 0.9824],
        [0.6360, 0.0023, 0.8916]])

In [104]:
# 1行
tensor[0]

tensor([0.0315, 0.1096, 0.5357])

In [105]:
# 1列
tensor[:, 0]

tensor([0.0315, 0.9299, 0.1956, 0.6360])

In [106]:
# 最後の行、列
print(tensor[-1])
print(tensor[:, -1])

tensor([0.6360, 0.0023, 0.8916])
tensor([0.5357, 0.1575, 0.9824, 0.8916])


In [107]:
# 置換え
tensor[:,-1] = 0
tensor

tensor([[0.0315, 0.1096, 0.0000],
        [0.9299, 0.7199, 0.0000],
        [0.1956, 0.3469, 0.0000],
        [0.6360, 0.0023, 0.0000]])

In [108]:
t1 = torch.cat([tensor, tensor], dim=1)
print(t1)

tensor([[0.0315, 0.1096, 0.0000, 0.0315, 0.1096, 0.0000],
        [0.9299, 0.7199, 0.0000, 0.9299, 0.7199, 0.0000],
        [0.1956, 0.3469, 0.0000, 0.1956, 0.3469, 0.0000],
        [0.6360, 0.0023, 0.0000, 0.6360, 0.0023, 0.0000]])


In [109]:
data = [[1, 2], [3, 4], [5, 6]]
tensor = torch.tensor(data)
tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [110]:
tensor.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [111]:
tensor * tensor

tensor([[ 1,  4],
        [ 9, 16],
        [25, 36]])

エラー  
tensor * tensor.T  
tensor @ tensor

In [112]:
y = tensor @ tensor.T
y

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

In [113]:
tensor.size(), tensor.T.size()

(torch.Size([3, 2]), torch.Size([2, 3]))

行列の勉強しようね

- matmul：は行列のかけ算を行う

In [114]:
# tensor @ tensor.Tと同じっぽい
y2 = tensor.matmul(tensor.T)
y2

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

In [122]:
piyo = y2 / (y2.max())
print(y2.dtype)
piyo

torch.int64


tensor([[0.0820, 0.1803, 0.2787],
        [0.1803, 0.4098, 0.6393],
        [0.2787, 0.6393, 1.0000]])

In [127]:
# 同じsizeでfloat型でランダムに数値を選んだだけ。
y3 = torch.rand_like(piyo)
# なんかrand_likeは0-1の範囲じゃないと計算されないらしい

y3

tensor([[0.8365, 0.0081, 0.8351],
        [0.8260, 0.8799, 0.4851],
        [0.6827, 0.9165, 0.5073]])

In [130]:
torch.matmul(piyo, piyo.T, out=y3)

tensor([[0.1169, 0.2669, 0.4168],
        [0.2669, 0.6092, 0.9516],
        [0.4168, 0.9516, 1.4864]])

In [133]:
# out=y3, 出力先はoutにしろよという意味
y3

tensor([[0.1169, 0.2669, 0.4168],
        [0.2669, 0.6092, 0.9516],
        [0.4168, 0.9516, 1.4864]])

In [135]:
z1 = tensor * tensor
z1

tensor([[ 1,  4],
        [ 9, 16],
        [25, 36]])

- mul: かけ算を示す

In [145]:
z2 = tensor.mul(tensor)
z2

tensor([[ 1,  4],
        [ 9, 16],
        [25, 36]])

In [143]:
piyo

tensor([[0.0820, 0.1803, 0.2787],
        [0.1803, 0.4098, 0.6393],
        [0.2787, 0.6393, 1.0000]])

In [142]:
# 確認
z3 = piyo.mul(piyo)
z3

tensor([[0.0067, 0.0325, 0.0777],
        [0.0325, 0.1680, 0.4088],
        [0.0777, 0.4088, 1.0000]])

独自の値を使っててドキュメントの流れと離れすぎた。一回もとに戻す

In [173]:
data = [[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]

tensor = torch.tensor(data)
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

- agg: 値をすべて集約（足し合わる）

In [154]:
agg = tensor.sum()
agg, type(agg)

(tensor(12.), torch.Tensor)

- .item: 要素を取り出す

In [155]:
agg_item = agg.item()
agg_item, type(agg_item)

(12.0, float)

- インプレース：add_, copy_  
`_`を使用して演算や変更が行われる。  

**注意**
> インプレース演算はメモリを節約しますが、履歴が即座に失われるため、微分計算を行う際に問題が発生する可能性があります。したがって、インプレース演算の使用は推奨されません。

In [183]:
tensor = torch.tensor(data)
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [184]:
# tensorに直接足し算をしているっぽい
tensor.add_(5)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [185]:
tensor

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

## Bridge（ブリッジ）

**numpyからtensorへ**  
CPU上のTensorとNumPy配列（ndarray）の間で、メモリを共有したまま相互に変換できる機能

In [186]:
t = torch.ones(5)
t

tensor([1., 1., 1., 1., 1.])

- 変数名.numpy()

In [188]:
n = t.numpy()
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [189]:
t.add_(1)
t

tensor([2., 2., 2., 2., 2.])

In [190]:
n

array([2., 2., 2., 2., 2.], dtype=float32)

メモリが共有されてるから、上書きされるとtensorも変わるのかな